name: Common Workflow

on:
  workflow_call:
    inputs:
      lint_script:
        required: true
        type: string

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout calling repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get changed files (push)
        id: changes
        run: |
          git fetch origin
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          cat changed_files.txt
          echo "CHANGED_FILES=$(paste -sd' ' changed_files.txt)" >> $GITHUB_ENV

      - name: Run lint script
        run: |
          chmod +x ${{ inputs.lint_script }}
          ./${{ inputs.lint_script }} $CHANGED_FILES
