name: Common Workflow

on:
  workflow_call:
    inputs:
      lint_script:
        required: true
        type: string

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout calling repo
        uses: actions/checkout@v4

      - name: Run lint script
        run: |
          chmod +x ${{ inputs.lint_script }}
          ./${{ inputs.lint_script }}
